In [0]:
import pandas as pd
import tarfile
import json
import numpy as np
import time
from google.colab import files

In [0]:
#Upload yelp_restraunt_raters.csv,yelp_restraunt_reviews.csv,yelp_restraunts.csv 
uploaded1 = files.upload()

Saving yelp_restraunt_raters.csv to yelp_restraunt_raters.csv
Saving yelp_restraunt_reviews.csv to yelp_restraunt_reviews.csv
Saving yelp_restraunts.csv to yelp_restraunts.csv

In [0]:
users = pd.read_csv('yelp_restraunt_raters.csv')
reviews = pd.read_csv('yelp_restraunt_reviews.csv')
restraunts = pd.read_csv('yelp_restraunts.csv')

In [0]:
restrauntlist = restraunts['categories'].tolist()

In [0]:
import collections as c

uniquewords = c.Counter()
for i in restrauntlist:
  words = i.split(', ')
  uniquewords.update(words)


del uniquewords['Restaurants']
del uniquewords['Food']

top100 = uniquewords.most_common(100)
print(set(top100))
print(top100[1][0])
print(type(top100))
categorylist = []
categorycounts = []
for i in top100:
  categorylist.append(i[0])
  categorycounts.append(i[1])

{('Steakhouses', 108), ('Pizza', 625), ('Bagels', 42), ('Tapas Bars', 108), ('Local Flavor', 45), ('Fish & Chips', 61), ('Mediterranean', 345), ('Modern European', 60), ('Comfort Food', 197), ('Grocery', 60), ('Persian/Iranian', 51), ('Fast Food', 633), ('Asian Fusion', 340), ('Tapas/Small Plates', 127), ('American (Traditional)', 419), ('Pakistani', 102), ('Chinese', 731), ('Bubble Tea', 56), ('Korean', 295), ('Falafel', 41), ('Food Stands', 49), ('Taiwanese', 59), ('Cajun/Creole', 41), ('Beer', 129), ('Canadian (New)', 712), ('Juice Bars & Smoothies', 194), ('Ice Cream & Frozen Yogurt', 120), ('Vegetarian', 257), ('Specialty Food', 366), ('Tea Rooms', 54), ('Caterers', 244), ('Coffee & Tea', 748), ('Bars', 1161), ('Italian', 669), ('Filipino', 49), ('Burgers', 501), ('Chicken Wings', 272), ('Sushi Bars', 419), ('Hot Dogs', 47), ('British', 48), ('Creperies', 40), ('Hot Pot', 34), ('Nightlife', 1213), ('French', 199), ('Desserts', 291), ('Gastropubs', 134), ('Salad', 309), ('Seafood', 279), ('Turkish', 47), ('Mexican', 299), ('Greek', 186), ('Caribbean', 188), ('Beer Bar', 46), ('Noodles', 122), ('Vegan', 222), ('Food Delivery Services', 103), ('Poutineries', 55), ('Gluten-Free', 173), ('Dim Sum', 81), ('Delis', 131), ('African', 42), ('Cafes', 751), ('Southern', 39), ('Food Court', 69), ('Spanish', 38), ('Tex-Mex', 58), ('Portuguese', 81), ('Donuts', 34), ('Sports Bars', 130), ('Shopping', 95), ('Arts & Entertainment', 134), ('Latin American', 90), ('Bakeries', 296), ('Buffets', 47), ('American (New)', 268), ('Music Venues', 57), ('Ramen', 69), ('Food Trucks', 38), ('Chicken Shop', 87), ('Thai', 316), ('Health Markets', 35), ('Japanese', 615), ('Wine Bars', 145), ('Cocktail Bars', 189), ('Indian', 388), ('Diners', 184), ('Lounges', 170), ('Pubs', 280), ('Imported Food', 50), ('Barbeque', 237), ('Breakfast & Brunch', 780), ('Middle Eastern', 361), ('Event Planning & Services', 341), ('Sandwiches', 781), ('Halal', 182), ('Wine & Spirits', 129), ('Venues & Event Spaces', 77), ('Soup', 109), ('Vietnamese', 226), ('Ethnic Food', 155)}
Bars
<class 'list'>

In [0]:
restfinal=[]
countfinal=[]
ratingfinal=[]

for i in categorylist:
  count = 0
  rating = 0
  final = 0
  for index, row in restraunts.iterrows():
    if i in row['categories']:
      count += 1
      rating += row['stars']
      final = rating / count
  if final > 0:
    restfinal.append(i)
    countfinal.append(count)
    ratingfinal.append(final)

In [0]:
d = {'Category': restfinal, 'Count': countfinal, 'Rating Average': ratingfinal}
df = pd.DataFrame(data=d)
df.sort_values(by=['Rating Average'], ascending=False)

              Category  Count  Rating Average
1                 Bars   1791        3.505025
0            Nightlife   1213        3.487222
2           Sandwiches    781        3.442382
3   Breakfast & Brunch    780        3.548077
4                Cafes    759        3.725955
..                 ...    ...             ...
95             Spanish     38        3.736842
96         Food Trucks     38        3.815789
97      Health Markets     35        3.800000
98              Donuts     34        2.985294
99             Hot Pot     34        3.338235

[100 rows x 3 columns]

In [0]:
df.to_csv('top100ratings.csv')
files.download('top100ratings.csv')

In [0]:
df.sort_values(by=['Count'], ascending=False)

              Category  Count  Rating Average
1                 Bars   1791        3.505025
0            Nightlife   1213        3.487222
2           Sandwiches    781        3.442382
3   Breakfast & Brunch    780        3.548077
4                Cafes    759        3.725955
..                 ...    ...             ...
95             Spanish     38        3.736842
96         Food Trucks     38        3.815789
97      Health Markets     35        3.800000
98              Donuts     34        2.985294
99             Hot Pot     34        3.338235

[100 rows x 3 columns]

In [0]:
df.sort_values(by=['Count'])

              Category  Count  Rating Average
99             Hot Pot     34        3.338235
98              Donuts     34        2.985294
97      Health Markets     35        3.800000
96         Food Trucks     38        3.815789
95             Spanish     38        3.736842
..                 ...    ...             ...
4                Cafes    759        3.725955
3   Breakfast & Brunch    780        3.548077
2           Sandwiches    781        3.442382
0            Nightlife   1213        3.487222
1                 Bars   1791        3.505025

[100 rows x 3 columns]

In [0]:
df.sort_values(by=['Rating Average'])

           Category  Count  Rating Average
29    Chicken Wings    272        2.823529
98           Donuts     34        2.985294
9         Fast Food    633        3.011058
74          Tex-Mex     58        3.060345
51      Sports Bars    130        3.165385
..              ...    ...             ...
35            Vegan    222        3.833333
71  Modern European     60        3.850000
72          Grocery     64        3.867188
63   Latin American     90        3.894444
84          Turkish     47        3.914894

[100 rows x 3 columns]